// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjbltipufenvjwpbfrpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqYmx0aXB1ZmVudmp3cGJmcnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3MTc4NzksImV4cCI6MjEwMzI5Mzg3OX0.pnhH4OFTbWeAy7DHj7Sk-RFYbL_-KxlAvhTUTKZ2WLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});